---
- name: create prometheus group
  group:
    name: "{{ prometheus_group_name }}"
    gid: "{{ prometheus_group_gid }}"
    state: present

- name: create prometheus user
  user:
    name: "{{ prometheus_user_name }}"
    uid: "{{ prometheus_user_uid }}"
    group: "{{ prometheus_group_name }}"
    shell: /bin/false
    createhome: no
    state: present

- name: download prometheus
  get_url:
    url: "{{ prometheus_download_url }}"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

- name: extract prometheus
  unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /var/tmp
    remote_src: yes

- name: create prometheus directories
  file:
    path: "{{ prometheus_home }}/{{ item.name }}"
    state: directory
    owner: "{{ prometheus_user_name }}"
    group: "{{ prometheus_group_name }}"
    mode: "{{ item.mode }}"
  with_items:
    - { name: "", mode: "0755" }
    - { name: "bin", mode: "0755" }
    - { name: "data", mode: "0700" }
    - { name: "etc", mode: "0700" }

- name: copy prometheus binaries
  copy:
    src: "/var/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_home }}/bin/{{ item }}"
    owner: "{{ prometheus_user_name }}"
    group: "{{ prometheus_group_name }}"
    mode: "0755"
    remote_src: yes
  with_items:
    - prometheus
    - promtool

- name: put configuration file
  template:
    src: config.yml.j2
    dest: "{{ prometheus_home }}/etc/config.yml"
    owner: "{{ prometheus_user_name }}"
    group: "{{ prometheus_group_name }}"
    mode: "0600"
  notify: restart prometheus

- name: put service file
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: restart prometheus

- name: prometheus is started
  systemd:
    name: prometheus
    state: started
