---
- name: create replication user
  mysql_user:
    name: repl
    password: "{{ mysql_repl_password }}"
    host: "{{ item }}"
    priv: '*.*:SUPER,REPLICATION SLAVE'
    state: present
  with_items:
    - 10.0.0.0/255.0.0.0

- name: remove anonymous mysql user
  mysql_user:
    name: ""
    state: absent
    host_all: yes

- name: remove test database
  mysql_db:
    name: test
    state: absent
