---
- name: create mysqld_exporter group
  group:
    name: "{{ mysqld_exporter_group_name }}"
    gid: "{{ mysqld_exporter_group_gid }}"
    state: present

- name: create mysqld_exporter user
  user:
    name: "{{ mysqld_exporter_user_name }}"
    uid: "{{ mysqld_exporter_user_uid }}"
    group: "{{ mysqld_exporter_group_name }}"
    shell: /bin/false
    createhome: no
    state: present

- name: download mysqld_exporter
  get_url:
    url: "{{ mysqld_exporter_download_url }}"
    dest: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64.tar.gz"

- name: extract prometheus
  unarchive:
    src: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64.tar.gz"
    dest: /var/tmp
    remote_src: yes

- name: create mysqld_exporter directories
  file:
    path: "{{ mysqld_exporter_home }}/{{ item.name }}"
    state: directory
    owner: "{{ mysqld_exporter_user_name }}"
    group: "{{ mysqld_exporter_group_name }}"
    mode: "{{ item.mode }}"
  with_items:
    - { name: "", mode: "0755" }
    - { name: "bin", mode: "0755" }
    - { name: "data", mode: "0700" }
    - { name: "etc", mode: "0700" }

- name: copy mysqld_exporter binaries
  copy:
    src: "/var/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/{{ item }}"
    dest: "{{ mysqld_exporter_home }}/bin/{{ item }}"
    owner: "{{ mysqld_exporter_user_name }}"
    group: "{{ mysqld_exporter_group_name }}"
    mode: "0755"
    remote_src: yes
  with_items:
    - mysqld_exporter

- name: put MySQL client configuration file
  template:
    src: my.cnf.j2
    dest: "{{ mysqld_exporter_home }}/etc/my.cnf"
    owner: "{{ mysqld_exporter_user_name }}"
    group: "{{ mysqld_exporter_group_name }}"
    mode: "0600"
  notify: restart mysqld_exporter

- name: put service file
  template:
    src: mysqld_exporter.service.j2
    dest: /etc/systemd/system/mysqld_exporter.service
  notify: restart mysqld_exporter

- name: mysqld_exporter is started
  systemd:
    name: mysqld_exporter
    state: started
