#
# [usage]
# ansible-playbook \
#   -e 'gce_project_id=[project]' \
#   -e 'gce_service_account_email=[email]' \
#   -e 'gce_credentials_file=[/path/to/credentials_file]' \
#   -e 'ansible_ssh_private_key_file=[/path/to/.ssh/google_compute_engine]'
#

- hosts: localhost
  gather_facts: no
  roles:
    - gce

- hosts: all
  gather_facts: no
  roles:
    - network
    - node_exporter
  become: yes

- hosts: mysql
  gather_facts: no
  roles:
    - mysql
    - mysqld_exporter
  become: yes

- hosts: monitor
  gather_facts: no
  roles:
    - prometheus
    - grafana
  become: yes
